version: "3.3"

services:
    ecomm-be:
        image: ecomm
        container_name: ecomm-be
        restart: always
        env_file:
            - ./env/prod.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        volumes:
            - ./:/opt/e_commerce
        tty: true
        network_mode: "host"
    
    db:
        image: postgres:12.4
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=e_commerce
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        env_file:
            - ./env/prod.env
        volumes:
            - ./:/opt/e_commerce
        tty: true
        network_mode: "host"

    redis:
        image: redis:6.0.8
        container_name: redis
        restart: always
        tty: true
        network_mode: "host"
        

