version: "3.3"

services:
    ecomm-be:
        image: e_comm/be:prod
        container_name: ecomm-be
        restart: always
        env_file:
            - ./env/prod.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        volumes:
            - ./:/opt/e_commerce
        tty: true
        network_mode: "host"
    
    db:
        image: postgres:12.4
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        env_file:
            - ./env/prod.env
        volumes:
            - ./:/opt/e_commerce
        tty: true
        network_mode: "host"
