# Generated by Django 3.2.3 on 2021-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
