# Generated by Django 3.2.3 on 2021-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_number', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
